version: '2'

services:
  db:
    image: rethinkdb
    command: rethinkdb --bind all --initial-password ${RETHINKDB_PASSWORD}
    ports:
      - "28015:28015"
    volumes:
      - rethink-data:/data

  web:
    build: ./livestatus/
    environment:
      RETHINKDB_HOST: "db"
      RETHINKDB_PASSWORD: "${RETHINKDB_PASSWORD}"
    depends_on:
      - db
    ports:
      - "80:8090"

volumes:
  caddy_certificates:
    driver: local
  rethink-data:
    driver: local
