default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  <<: *default
  database: logsfeed_test

development:
  <<: *default
  database: logsfeed

staging:
  <<: *default
  database: logsfeed

production:
  <<: *default
  database: logsfeed
